"""Add WebAuthn fields

Revision ID: 28978d7e74e6
Revises: 
Create Date: 2025-07-30 07:00:35.748509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28978d7e74e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webauthn_credential_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('webauthn_public_key', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('webauthn_sign_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('webauthn_backed_up', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint("uq_webauthn_credential_id", ['webauthn_credential_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('webauthn_backed_up')
        batch_op.drop_column('webauthn_sign_count')
        batch_op.drop_column('webauthn_public_key')
        batch_op.drop_column('webauthn_credential_id')

    # ### end Alembic commands ###
