"""update database

Revision ID: c2da27e6e0e7
Revises: 28978d7e74e6
Create Date: 2025-07-30 19:59:57.724510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2da27e6e0e7'
down_revision = '28978d7e74e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_webauthn_credential_id'), type_='unique')
        batch_op.drop_column('webauthn_credential_id')
        batch_op.drop_column('webauthn_sign_count')
        batch_op.drop_column('webauthn_public_key')
        batch_op.drop_column('webauthn_backed_up')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webauthn_backed_up', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('webauthn_public_key', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('webauthn_sign_count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('webauthn_credential_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_webauthn_credential_id'), ['webauthn_credential_id'])

    # ### end Alembic commands ###
